### ISSUE TITLE
Consider using SLF4J stable version

### ISSUE THREAD

**Issue by AlexFalappa** [cloudconvert/cloudconvert-java#21]
SLF4J `2.0.0-alpha1` uses a backward incompatible method for finding logging implementations and do not play nicely with a lot of code bases stuck with SLF4J 1.7.x and a compliant logging implementation (e.g. logback).

More details on the backward incompatibility here:
http://www.slf4j.org/faq.html#changesInVersion18

**Comment by josiasmontag** [comment]
I would accept a PR for this :)
