### ISSUE TITLE
Error during the upload of single file 

### ISSUE THREAD

**Issue by Pavansid94** [cloudconvert/cloudconvert-java#24]
Hello, 

I'm following the Upload method as suggested by the official SDK. But there seems to be an issue. Every time i try to upload a single file, i get the same error with message "**POST requires exactly one file upload per request.**". Details are attached. 
![image](https://user-images.githubusercontent.com/56548270/102906420-e2fc1b00-4474-11eb-876a-bf94074e3e31.png)
![image](https://user-images.githubusercontent.com/56548270/102906687-46864880-4475-11eb-9a02-8c6efafa93aa.png)

Any help would be appreciated!

**Comment by josiasmontag** [comment]
Are you using the latest version 1.0.4? 
Also, do the integration tests of the SDK work on your system?

**Comment by Pavansid94** [comment]
Yes, this is the latest version.
The integration seems alright and i'm able to also do a **UploadUsingURL** sucessfully, but this particular use case seems to fail.

**Comment by josiasmontag** [comment]
I would suggest to run and debug [uploadImportInputStreamAndExportUrlTaskLifecycle()](https://github.com/cloudconvert/cloudconvert-java/blob/master/src/test/java/com/cloudconvert/test/integration/ImportsAndExportsIntegrationTest.java#L108) and check what is different in your case. In specific, how does `inputStream` look like, is it readable etc.

**Comment by Pavansid94** [comment]
Okay, alright, after inspection, i see no major differences in the `InputStream` of uploadImportInputStreamAndExportUrlTaskLifecycle() and mine (i can share you the screenshots for each of those contents in case you need). But i wonder why it is considering the request as containing Multiple files though?

**Comment by Pavansid94** [comment]
Okay, a delayed update, a look at` jobsIntegrationTest#mergeFileTaskAsJobLifecycle()` at [[Line 92]](https://github.com/cloudconvert/cloudconvert-java/blob/master/src/test/java/com/cloudconvert/test/integration/JobsIntegrationTest.java#L92) gave me the right way of using the upload.  It's now working and i'll close this issue myself, but might want to update the README with regards to upload because that piece of code doesn't work.
