### ISSUE TITLE
Is the new cloudconvert API compatible with JDK 1.7?

### ISSUE THREAD

**Issue by arajendranUAIG** [cloudconvert/cloudconvert-java#25]
Hi,
We have been using cloud convert java API V1 with JDK1.7. And looking to upgrade into new V2 api version.
- Is this new version V2 API compatible with JDK1.7?
- Also, I tried with JDK 1.8 (jdk1.8.0_241), still see bunch of files with compilation issues.
What is the precise version JDK1.8 I need for this V2 API? 

Thank you

**Comment by josiasmontag** [comment]
It requires JDK8+
We have tested with the latest JDK8 version only.

**Comment by arajendranUAIG** [comment]
> It requires JDK8+
> We have tested with the latest JDK8 version only.

Hi Josias
Thank you so much for the quick update.
Am trying to setup using JDK 1.8 (jdk1.8.0_241), and having bunch of compilation issues in eclipse.
Am I missing any step after downloading the java-api maven project from github?
Thank you in advance!!

![image](https://user-images.githubusercontent.com/61283389/105064411-cbe82300-5a4a-11eb-8829-e189cbcd0fc5.png)

**Comment by josiasmontag** [comment]
It seems the annotations from Lombok are not processed in your IDE.
See: https://www.baeldung.com/lombok-ide

**Comment by arajendranUAIG** [comment]
Yes. That was it!!  after installing lombok, the compilation errors are gone! Thank you so much.
Let me setup and test some PDF conversion using this new API.

And, Looks like the support for  couldconvert api V1 is expiring by January,2022.
We mainly use cloudconvert for PDF conversion process from our core application.
Our core application requires to be on JDK1.7, don't think we can upgrade to JDK 1.8 soon.
Am not sure if you could give some update or should we contact the cloudconvert support personals on this.
Do you have any advice if we can continue to use Java API V1 beyond January-2022? or any other suggestions.
Thank you again!

**Comment by josiasmontag** [comment]
API v1 lifetime will not be extended after January 2022. If you really need to stay on Java 7, you could implement API v2 on your own.
