### ISSUE TITLE
Not able to use Base64 and raw type for import

### ISSUE THREAD

**Issue by iti-gupta2** [cloudconvert/cloudconvert-java#31]
I'm trying to convert base64 and raw type of import data into another format. I could find Request DTOs for the other type of import options available(URL,S3,GoogleCloudStorage, AzureBlob,SFTP,OpenStack) but I could not find any method to access the base46 and raw endpoints. Could please tell me if I'm missing something here?

**Comment by josiasmontag** [comment]
They are not implemented in the SDK yet.

We will add them at some point. In meantime, PRs are welcome.

**Comment by iti-gupta2** [comment]
Sure! Thanks for the quick response.
