### ISSUE TITLE
Getting Unauthorized even though environment variables are set

### ISSUE THREAD

**Issue by eszterszilagyi** [cloudconvert/cloudconvert-java#39]
<img width="669" alt="Screenshot 2021-09-29 at 11 25 40" src="https://user-images.githubusercontent.com/7317523/135231599-a91c5f42-7349-44d6-bc6f-1f6ceaef1e83.png">

`
Result<JobResponse> result = client.jobs().create(
                ImmutableMap.of(
                    "upload",
                    new S3ImportRequest()
                        .setBucket(exportDestination)
                        .setKey(tmpFile.getName())
                        .setEndpoint(s3Endpoint)
                        .setSecretAccessKey(credentials.getAWSSecretKey())
                        .setAccessKeyId(credentials.getAWSAccessKeyId()),
                    "convert",
                    new ConvertFilesTaskRequest()
                        .setEngine("inkscape")
                        .setInput("upload")
                        .setInputFormat("svg")
                        .setOutputFormat("dxf")
                        .setFilename(tmpFile.getName()),
                    "export-result",
                    new S3ExportRequest()
                        .setBucket(exportDestination)
                        .setKey(tmpFile.getName())
                        .setEndpoint(s3Endpoint)
                        .setSecretAccessKey(credentials.getAWSSecretKey())
                        .setAccessKeyId(credentials.getAWSAccessKeyId())
                )
            );
`

<img width="635" alt="Screenshot 2021-09-29 at 11 25 27" src="https://user-images.githubusercontent.com/7317523/135231621-dc40fe6c-5e37-4836-925e-fff289b2c76c.png">

Why?

**Comment by josiasmontag** [comment]
This is not a valid API key.

This is the issue tracker for the Java SDK. Please do not use the issue tracker for support requests. Thanks.
